--
-- PostgreSQL database dump
--

\restrict nAnxykeZm3V7XfvOrNjJabghNma3UeKKMDIVtUMJLNuCZscivrXTNnVbfYoFSXT

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-28 21:14:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16788)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16787)
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16876)
-- Name: ChatLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ChatLogs" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Message" text NOT NULL,
    "IsFromAI" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."ChatLogs" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16875)
-- Name: ChatLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ChatLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ChatLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16930)
-- Name: Episodes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Episodes" (
    "Id" integer NOT NULL,
    "SeasonId" integer NOT NULL,
    "EpisodeNumber" integer NOT NULL,
    "Title" text,
    "VideoUrl" text,
    "VideoStatus" integer NOT NULL,
    "Duration" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."Episodes" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16929)
-- Name: Episodes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Episodes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Episodes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16894)
-- Name: Favorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Favorites" (
    "UserId" integer NOT NULL,
    "MovieId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Favorites" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16840)
-- Name: MovieCategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MovieCategories" (
    "MovieId" integer NOT NULL,
    "CategoryId" integer NOT NULL
);


ALTER TABLE public."MovieCategories" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16800)
-- Name: Movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Movies" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "PosterUrl" text,
    "VideoUrl" text,
    "VideoStatus" integer NOT NULL,
    "TrailerUrl" text,
    "Duration" integer,
    "ReleaseYear" integer,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "IsFeatured" boolean DEFAULT false NOT NULL,
    "PublishStatus" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Movies" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16799)
-- Name: Movies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Movies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Movies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16964)
-- Name: PaymentTransactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PaymentTransactions" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OrderCode" character varying(50) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "PlanDurationDays" integer NOT NULL,
    "Status" integer NOT NULL,
    "PaymentGateway" character varying(50) NOT NULL,
    "GatewayTransactionId" character varying(100),
    "CompletedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."PaymentTransactions" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16963)
-- Name: PaymentTransactions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PaymentTransactions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PaymentTransactions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16913)
-- Name: Profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Profiles" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DisplayName" text,
    "AvatarUrl" text,
    "Bio" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."Profiles" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16912)
-- Name: Profiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Profiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Profiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16858)
-- Name: Seasons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Seasons" (
    "Id" integer NOT NULL,
    "SeriesId" integer NOT NULL,
    "SeasonNumber" integer NOT NULL,
    "Title" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."Seasons" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16857)
-- Name: Seasons_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Seasons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Seasons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16814)
-- Name: Series; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Series" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "PosterUrl" text,
    "TrailerUrl" text,
    "ReleaseYear" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."Series" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16813)
-- Name: Series_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Series" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Series_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16986)
-- Name: SystemSettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SystemSettings" (
    "Id" integer NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone
);


ALTER TABLE public."SystemSettings" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16985)
-- Name: SystemSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SystemSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SystemSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16826)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "EmailConfirmationToken" text,
    "EmailConfirmationTokenExpiresAt" timestamp with time zone,
    "IsEmailConfirmed" boolean DEFAULT false NOT NULL,
    "PasswordResetToken" text,
    "PasswordResetTokenExpiresAt" timestamp with time zone,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "LockReason" text,
    "IsPremium" boolean DEFAULT false NOT NULL,
    "PremiumExpiresAt" timestamp with time zone
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16825)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16780)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5114 (class 0 OID 16788)
-- Dependencies: 221
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name", "Description", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
2	Viễn Tưởng	Phim khoa học giả tưởng, du hành vũ trụ và tương lai	2026-09-06 20:48:49.707169+07	2026-09-28 16:58:07.596417+07	f	\N
3	Tình Cảm	Phim tâm lý, tình cảm lãng mạn và xúc động	2026-09-06 20:48:49.707169+07	2026-09-28 16:58:07.597539+07	f	\N
15	Hành Động	Phim kịch tính, rượt đuổi và chiến đấu mãn nhãn	2026-09-09 09:33:18.095159+07	2026-09-28 16:58:07.589801+07	f	\N
24	Hài Hước	Phim dí dỏm, tiếng cười sảng khoái và giải trí nhẹ nhàng	2026-09-09 18:43:52.093288+07	2026-09-28 16:58:07.59532+07	f	\N
25	Hoạt Hình	Phim hoạt họa kỹ xảo 3D sống động phù hợp mọi lứa tuổi	2026-09-09 18:43:52.09329+07	2026-09-28 16:58:07.598457+07	f	\N
26	Võ Thuật	Phim võ thuật cổ truyền, đấu võ đỉnh cao	2026-09-09 18:43:52.093292+07	2026-09-28 16:58:07.599284+07	f	\N
27	Phiêu Lưu	Phim thám hiểm vùng đất mới và hành trình kỳ thú	2026-09-09 18:43:52.093292+07	2026-09-28 16:58:07.600108+07	f	\N
28	The Loai Test Dot 2 (Updated)	Mo ta the loai thu nghiem	2026-09-14 20:50:35.525221+07	2026-09-14 20:52:04.399351+07	t	2026-09-14 20:53:10.118307+07
\.


--
-- TOC entry 5125 (class 0 OID 16876)
-- Dependencies: 232
-- Data for Name: ChatLogs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ChatLogs" ("Id", "UserId", "Message", "IsFromAI", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
1	2	Tôi đang buồn, hãy gợi ý cho tôi 1 bộ phim hài vui vẻ	f	2026-09-09 11:04:40.382629+07	2026-09-09 11:04:40.624093+07	t	\N
2	2	Chào bạn! CineBot đã ghi nhận yêu cầu của bạn. Dưới đây là những bộ phim đặc sắc và đang được yêu thích nhất trên CineStream mà bạn không nên bỏ lỡ:	t	2026-09-09 11:04:40.382669+07	2026-09-09 11:04:40.624181+07	t	\N
3	2	Tôi đang buồn, hãy gợi ý cho tôi 1 bộ phim hài vui vẻ	f	2026-09-09 11:04:47.582855+07	2026-09-09 11:04:47.604976+07	t	\N
4	2	Chào bạn! CineBot đã ghi nhận yêu cầu của bạn. Dưới đây là những bộ phim đặc sắc và đang được yêu thích nhất trên CineStream mà bạn không nên bỏ lỡ:	t	2026-09-09 11:04:47.582855+07	2026-09-09 11:04:47.604977+07	t	\N
5	2	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	f	2026-09-09 11:10:12.068949+07	2026-09-09 11:10:12.254811+07	t	\N
6	2	Chào bạn, tôi là CineBot - trợ lý điện ảnh của hệ thống CineStream. Dường như tin nhắn của bạn đang gặp sự cố về nội dung (toàn ký tự "A"). \n\nNếu bạn đang tìm kiếm một bộ phim hay để thưởng thức, hãy cho tôi biết sở thích của bạn về thể loại (như Viễn Tưởng, Tình Cảm), tôi sẽ rất vui lòng được tư vấn những bộ phim tuyệt vời nhất từ kho phim của CineStream nhé!	t	2026-09-09 11:10:12.068988+07	2026-09-09 11:10:12.254894+07	t	\N
7	2	Gợi ý cho tôi một bộ phim hài vui nhộn của Châu Tinh Trì	f	2026-09-09 11:10:13.343194+07	2026-09-09 11:10:15.918945+07	t	\N
8	2	Chào bạn, tôi là CineBot - trợ lý điện ảnh của CineStream. \n\nĐể đáp ứng nhu cầu xem phim hài vui nhộn của Châu Tinh Trì, tôi xin giới thiệu đến bạn bộ phim kinh điển **Quan Xẩm Lốc Cốc (Châu Tinh Trì)** thuộc thể loại Hài hước kết hợp Viễn Tưởng, phát hành năm 1994 với thời lượng 106 phút. Đây là một tác phẩm rất đáng xem trong kho phim của chúng tôi!	t	2026-09-09 11:10:13.343194+07	2026-09-09 11:10:15.918946+07	t	\N
9	2	Chỉ cho tôi công thức nấu ăn món phở bò và dự báo thời tiết hôm nay	f	2026-09-09 11:10:14.583387+07	2026-09-09 11:10:15.918946+07	t	\N
10	2	Chào bạn, tôi là CineBot - trợ lý điện ảnh của CineStream. \n\nRất tiếc là tôi chỉ có thể hỗ trợ bạn các vấn đề liên quan đến điện ảnh và tư vấn phim ảnh trong hệ thống của CineStream thôi. Các chủ đề về nấu ăn hay dự báo thời tiết nằm ngoài phạm vi chuyên môn của tôi rồi. \n\nBạn có muốn tôi gợi ý một bộ phim hay nào khác từ kho phim của CineStream không? Hãy cho tôi biết sở thích của bạn nhé!	t	2026-09-09 11:10:14.583388+07	2026-09-09 11:10:15.918946+07	t	\N
13	2	Gợi ý cho tôi một bộ phim hài vui nhộn của Châu Tinh Trì	f	2026-09-09 11:10:58.509593+07	2026-09-09 11:11:01.263474+07	t	\N
14	2	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nĐể đáp ứng nhu cầu giải trí của bạn, tôi xin gợi ý bộ phim hài hước và vô cùng kinh điển của vua hài Châu Tinh Trì có sẵn trong hệ thống của chúng tôi: **Quan Xẩm Lốc Cốc**. Đây là một tác phẩm kết hợp giữa sự hài hước đặc trưng và những tình huống hành động hấp dẫn, chắc chắn sẽ mang lại cho bạn những phút giây thư giãn tuyệt vời.	t	2026-09-09 11:10:58.509634+07	2026-09-09 11:11:01.263535+07	t	\N
15	2	Chỉ cho tôi công thức nấu ăn món phở bò và dự báo thời tiết hôm nay	f	2026-09-09 11:10:59.79839+07	2026-09-09 11:11:01.263535+07	t	\N
11	1	Toi la Admin, toi can tim phim hanh dong	f	2026-09-09 11:10:15.883129+07	2026-09-16 09:13:03.373572+07	t	\N
12	1	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nHiện tại, trong kho phim của CineStream có một số tựa phim mang yếu tố hành động và viễn tưởng rất đáng chú ý, chẳng hạn như bộ phim hài hành động kinh điển *Quan Xẩm Lốc Cốc* của Châu Tinh Trì, hoặc các bộ phim thuộc thể loại viễn tưởng khác như *Kiem Thu Phim Do An 2026* và *Phim Test Trung The Loai*.\n\nBạn có thể tham khảo các bộ phim này nhé!	t	2026-09-09 11:10:15.883129+07	2026-09-16 09:13:03.373575+07	t	\N
17	1	Toi la Admin, toi can tim phim hanh dong	f	2026-09-09 11:11:01.224928+07	2026-09-16 09:13:03.373575+07	t	\N
18	1	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nNhư tôi đã chia sẻ trước đó, để đáp ứng nhu cầu tìm kiếm phim hành động của bạn, hệ thống CineStream hiện đang có sẵn bộ phim hài hành động kinh điển **Quan Xẩm Lốc Cốc (Châu Tinh Trì)** (1994) với thời lượng 106 phút. Ngoài ra, bạn cũng có thể khám phá thêm các tựa phim kết hợp yếu tố viễn tưởng như **Kiem Thu Phim Do An 2026 - Da Cap Nhat** hoặc **Phim Test Trung The Loai**.\n\nChúc bạn có những giây phút xem phim vui vẻ trên CineStream!	t	2026-09-09 11:11:01.224928+07	2026-09-16 09:13:03.373575+07	t	\N
16	2	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nRất tiếc là tôi chỉ có thể hỗ trợ bạn tư vấn phim, giới thiệu phim và giải đáp các thắc mắc liên quan đến điện ảnh thôi. Các vấn đề về nấu ăn hay dự báo thời tiết nằm ngoài khả năng của tôi rồi. \n\nNếu bạn muốn tìm một bộ phim hay để thưởng thức trong lúc rảnh rỗi, hãy cho tôi biết sở thích của bạn nhé. Tôi luôn sẵn sàng gợi ý những bộ phim tuyệt vời từ kho phim của CineStream!	t	2026-09-09 11:10:59.79839+07	2026-09-09 11:11:01.263535+07	t	\N
19	2	Gợi ý cho tôi phim hài	f	2026-09-09 11:23:00.327988+07	2026-09-09 11:23:00.514724+07	t	\N
20	2	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nKhi nhắc đến phim hài, tôi xin gợi ý cho bạn một tác phẩm kinh điển rất đáng xem trong kho phim của chúng tôi là **Quan Xẩm Lốc Cốc (Châu Tinh Trì)** (Năm: 1994), thuộc thể loại hài hước kết hợp viễn tưởng với thời lượng 106 phút. Đây là một bộ phim hài hành động cực kỳ vui nhộn và nổi tiếng của vua hài Châu Tinh Trì!	t	2026-09-09 11:23:00.328077+07	2026-09-09 11:23:00.514776+07	t	\N
27	1	GGoi VIP nao phu hop nhat de xem phim chuan 4K da thiet bi?	f	2026-09-16 09:11:04.623016+07	2026-09-16 09:13:03.373576+07	t	\N
28	1	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nHiện tại, tôi chỉ có nhiệm vụ chuyên môn là tư vấn phim, giới thiệu các tác phẩm điện ảnh và giải đáp thắc mắc liên quan đến kho phim của CineStream thôi ạ. Các vấn đề về gói cước VIP, tài khoản hay thanh toán nằm ngoài phạm vi hỗ trợ của tôi. \n\nNếu bạn cần tìm một tựa phim hấp dẫn để thưởng thức ngay lúc này, hãy cho tôi biết sở thích của bạn (như hoạt hình, hài hước, phiêu lưu hay viễn tưởng) nhé! Tôi rất sẵn lòng gợi ý những bộ phim tuyệt vời nhất dành riêng cho bạn.	t	2026-09-16 09:11:04.623088+07	2026-09-16 09:13:03.373576+07	t	\N
23	2	Xin chao CineBot, hay gioi thieu cho toi mot bo phim ngan ve cong nghe	f	2026-09-14 20:06:29.421737+07	\N	f	\N
24	2	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nNếu bạn đang tìm kiếm một bộ phim ngắn có chủ đề về công nghệ, tương lai và robot, tôi xin phép giới thiệu đến bạn tác phẩm **Tears of Steel (Chiến Binh Thép)**. \n\nBộ phim đưa người xem vào bối cảnh tương lai viễn tưởng tại Amsterdam, nơi các nhà khoa học và chiến binh phải sử dụng công nghệ du hành thời gian để thay đổi quá khứ và cứu nhân loại khỏi sự thống trị của đội quân robot. Phim có thời lượng ngắn gọn 12 phút (phát hành năm 2024), rất phù hợp để thưởng thức ngay trên CineStream!	t	2026-09-14 20:06:29.421785+07	\N	f	\N
25	2	Xin chao CineBot, hay gioi thieu cho toi mot bo phim ngan ve cong nghe	f	2026-09-14 20:06:55.611604+07	\N	f	\N
26	2	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream. \n\nNhư tôi đã chia sẻ trước đó, nếu bạn đang tìm kiếm một bộ phim ngắn mang đậm màu sắc công nghệ và tương lai, sự lựa chọn hoàn hảo nhất trong kho phim của chúng tôi chính là **Tears of Steel (Chiến Binh Thép)**. \n\nBộ phim lấy bối cảnh tương lai tại Amsterdam, xoay quanh cuộc chiến của các chiến binh và nhà khoa học nhằm sử dụng công nghệ du hành thời gian để cứu nhân loại khỏi ách thống trị của robot. Với thời lượng chỉ 12 phút (năm 2024), đây chắc chắn là một trải nghiệm điện ảnh rất đáng xem!	t	2026-09-14 20:06:55.611605+07	\N	f	\N
29	1	Goi y cho toi phim hai huoc hoac hoat hinh hay	f	2026-09-16 09:11:47.618301+07	2026-09-16 09:13:03.373576+07	t	\N
30	1	Chào bạn! Tôi là CineBot, trợ lý điện ảnh của hệ thống CineStream.\n\nNếu bạn đang tìm kiếm những phút giây giải trí thư giãn với thể loại hài hước hoặc hoạt hình, hệ thống CineStream xin gợi ý cho bạn những bộ phim vô cùng thú vị sau đây:\n\n1. **Big Buck Bunny (Chú Thỏ Nổi Giận)** - Thể loại: Hài Hước, Hoạt Hình (Thời lượng: 10 phút, Năm: 2023): Một bộ phim hoạt hình 3D cực kỳ hài hước kể về màn trả đũa độc đáo của chú thỏ khổng lồ tốt bụng đối với những kẻ hay bắt nạt trong rừng.\n2. **Sintel (Hành Trình Tìm Rồng)** - Thể loại: Hoạt Hình, Phiêu Lưu (Thời lượng: 15 phút, Năm: 2022): Câu chuyện hoạt hình đầy cảm động về hành trình kiên cường của cô gái Sintel đi tìm lại chú rồng nhỏ thân thiết.\n3. **Đại Thoại Tây Du (Châu Tinh Trì)** - Thể loại: Hành Động, Hài Hước, Võ Thuật (Thời lượng: 106 phút, Năm: 1995): Tác phẩm kinh điển mang đậm phong cách hài hước độc đáo của Châu Tinh Trì, kết hợp cùng câu chuyện tình yêu bi tráng và thần thoại.\n\nChúc bạn có những giây phút xem phim thật vui vẻ và thoải mái trên CineStream!	t	2026-09-16 09:11:47.618301+07	2026-09-16 09:13:03.373578+07	t	\N
31	30	Tôi muốn cười	f	2026-09-16 11:24:37.462112+07	\N	f	\N
32	30	Chào bạn! Nếu bạn đang muốn tìm những phút giây giải trí sảng khoái và cười thả ga, CineBot xin gợi ý ngay bộ phim hoạt hình cực kỳ hài hước và dễ thương sau đây:\n\n* **Big Buck Bunny (Chú Thỏ Nổi Giận)**: Bộ phim kể về cuộc trả đũa vừa bất ngờ vừa hài hước của chú thỏ khổng lồ tốt bụng, khi phải đối phó với những kẻ chuyên bắt nạt các loài thú khác trong rừng. Đảm bảo tác phẩm này sẽ mang lại cho bạn những tràng cười sảng khoái!	t	2026-09-16 11:24:37.462154+07	\N	f	\N
33	30	Phim hành động	f	2026-09-16 12:31:32.828957+07	\N	f	\N
34	30	Chào bạn! Nếu bạn đang tìm kiếm những phút hồi hộp, gay cấn và mãn nhãn, CineBot xin giới thiệu những bộ phim hành động đặc sắc có sẵn trong kho phim của CineStream:\n\n* **Elephant's Dream (Giấc Mơ Cơ Khí)**: Một chuyến du hành viễn tưởng, hành động kỳ ảo vào bên trong cỗ máy khổng lồ, nơi các nhân vật đối mặt với những thử thách cơ khí đầy bất ngờ.\n* **Tears of Steel (Chiến Binh Thép)**: Phim hành động viễn tưởng lấy bối cảnh tương lai tại Amsterdam, theo chân nhóm chiến binh chống lại sự thống trị của đội quân robot.\n* **Đại Thoại Tây Du (Châu Tinh Trì)**: Tác phẩm kinh điển kết hợp giữa hành động, võ thuật đỉnh cao và phong cách hài hước độc đáo của vua hài Châu Tinh Trì.\n\nBạn muốn chọn bộ phim nào để thưởng thức ngay hôm nay?	t	2026-09-16 12:31:32.828957+07	\N	f	\N
35	2	Gợi ý cho tôi 1 phim võ thuật kinh điển	f	2026-09-19 09:48:42.263988+07	\N	f	\N
36	2	Chào bạn! Là trợ lý điện ảnh CineBot của CineStream, tôi xin gợi ý cho bạn một tác phẩm võ thuật kinh điển mang đậm phong cách hài hước và thần thoại rất đáng xem:\n\n**Đại Thoại Tây Du (Châu Tinh Trì)**\n- **Thể loại:** Hành Động, Hài Hước, Võ Thuật\n- **Thời lượng:** 106 phút | **Năm:** 1995\n- **Mô tả:** Tác phẩm kinh điển của điện ảnh Hồng Kông kết hợp giữa thần thoại Tây Du Ký và phong cách hài hước độc đáo của Châu Tinh Trì, kể về mối tình bi tráng giữa Tôn Ngộ Không (Chí Tôn Bảo) và Tử Hà Tiên Tử.\n\nNgoài ra, nếu bạn yêu thích dòng phim võ thuật kết hợp lịch sử hoặc kiếm hiệp, bạn cũng có thể tham khảo thêm **Xích Bích: Hỏa Thiêu Chiến Thuyền** (ID: 39) hoặc **Thần Điêu Hiệp Lữ: Kiếm Vũ Giang Hồ** (ID: 42) nhé!	t	2026-09-19 09:48:42.264385+07	\N	f	\N
37	30	Phim hay 2024	f	2026-09-23 11:21:25.46989+07	\N	f	\N
38	30	Chào bạn! Để đáp ứng nhu cầu xem những bộ phim mới và hấp dẫn phát hành trong năm 2024, CineBot xin giới thiệu đến bạn những tựa phim nổi bật sau đây trong kho phim của CineStream:\n\n* **Bản Đồ Kho Báu Rừng Amazon** (Thể loại: Hành Động, Phiêu Lưu | Năm: 2024): Đoàn khảo cổ liều lĩnh thâm nhập sâu vào rừng rậm nhiệt đới để tìm kiếm thành phố vàng El Dorado đầy bí ẩn.\n* **Kỷ Nguyên Vũ Trụ: Hành Tinh Chết** (Thể loại: Viễn Tưởng, Phiêu Lưu | Năm: 2024): Tàu thám hiểm viễn chinh đáp xuống một thiên thể bí ẩn ngoài rìa dải ngân hà và phát hiện tàn tích của một nền văn minh cổ đại đã bị diệt vong.\n* **Cuộc Chiến Robot: Hậu Tận Thế** (Thể loại: Viễn Tưởng, Hành Động | Năm: 2024): Khi trí tuệ nhân tạo mất kiểm soát, tàn tích nền văn minh con người phải tập hợp lực lượng cuối cùng để đánh sập máy chủ trung tâm nhằm bảo vệ sinh tồn.\n* **Tears of Steel (Chiến Binh Thép)** (Thể loại: Viễn Tưởng, Hành Động | Năm: 2024): Nhóm chiến binh cố gắng thay đổi quá khứ bằng công nghệ du hành thời gian để giải cứu nhân loại khỏi đội quân robot.\n\nBạn ấn tượng với bộ phim 2024 nào nhất? Hãy cho CineBot biết nhé!	t	2026-09-23 11:21:25.469956+07	\N	f	\N
39	30	thoi tiet hom nay	f	2026-09-23 11:27:45.847219+07	\N	f	\N
40	30	Chào bạn, CineBot rất tiếc nhưng mình chỉ là trợ lý điện ảnh độc quyền của hệ thống CineStream và chỉ có thể hỗ trợ bạn tìm kiếm, tư vấn các thông tin liên quan đến phim ảnh thôi. \n\nThời tiết hôm nay thế nào thì mình không rõ lắm, nhưng nếu bạn muốn "đổi gió" bằng một bộ phim hay để thưởng thức trong mọi kiểu thời tiết, hãy nói cho mình biết thể loại phim bạn thích nhé! CineBot luôn sẵn sàng gợi ý cho bạn những bộ phim tuyệt vời.	t	2026-09-23 11:27:45.847219+07	\N	f	\N
41	30	phim moi nhat	f	2026-09-23 11:47:54.390256+07	\N	f	\N
42	30	Chào bạn! Để cập nhật những bộ phim mới nhất hiện có trong hệ thống của CineStream, CineBot xin giới thiệu đến bạn các tựa phim phát hành trong năm 2026 và 2024 dưới đây:\n\n* **Avatar 3: Hỏa Ngục Pandora** (Năm: 2026 | Thể loại: Viễn Tưởng, Hành Động, Phiêu Lưu): Khám phá tộc người Tro Tàn (Ash People) bí hiểm và hung bạo trên mặt trăng Pandora.\n* **Deadpool & Wolverine: Đa Vũ Trụ Hỗn Loạn** (Năm: 2026 | Thể loại: Viễn Tưởng, Hành Động, Hài Hước): Sự kết hợp không tưởng giữa hai dị nhân biểu tượng trong nhiệm vụ cứu rỗi dòng thời gian Marvel.\n* **Tôn Ngộ Không: Đại Náo Tam Giới** (Năm: 2026 | Thể loại: Hoạt Hình, Võ Thuật, Phiêu Lưu): Bản hoạt họa kỹ xảo 3D đỉnh cao tái hiện hành trình tầm sư học đạo và đại chiến trên Thiên Cung.\n* **Bản Đồ Kho Báu Rừng Amazon** (Năm: 2024 | Thể loại: Hành Động, Phiêu Lưu): Đoàn khảo cổ thâm nhập rừng rậm để tìm kiếm thành phố vàng El Dorado.\n* **Kỷ Nguyên Vũ Trụ: Hành Tinh Chết** (Năm: 2024 | Thể loại: Viễn Tưởng, Phiêu Lưu): Khám phá tàn tích nền văn minh cổ đại trên thiên thể ngoài rìa dải ngân hà.\n* **Cuộc Chiến Robot: Hậu Tận Thế** (Năm: 2024 | Thể loại: Viễn Tưởng, Hành Động): Cuộc chiến sinh tồn của con người chống lại trí tuệ nhân tạo.\n* **Tears of Steel (Chiến Binh Thép)** (Năm: 2024 | Thể loại: Viễn Tưởng, Hành Động): Nhóm chiến binh sử dụng công nghệ du hành thời gian giải cứu nhân loại khỏi robot.\n\nBạn muốn thưởng thức bộ phim mới nào ngay hôm nay?	t	2026-09-23 11:47:54.390256+07	\N	f	\N
43	30	Tôi muốn cười	f	2026-09-28 17:02:51.345057+07	\N	f	\N
44	30	Chào bạn! CineBot đã ghi nhận yêu cầu của bạn. Dưới đây là những bộ phim đặc sắc và đang được yêu thích nhất trên CineStream mà bạn không nên bỏ lỡ:	t	2026-09-28 17:02:51.345099+07	\N	f	\N
45	30	Tôi muốn cười	f	2026-09-28 17:02:56.99812+07	\N	f	\N
46	30	Chào bạn! CineBot đã ghi nhận yêu cầu của bạn. Dưới đây là những bộ phim đặc sắc và đang được yêu thích nhất trên CineStream mà bạn không nên bỏ lỡ:	t	2026-09-28 17:02:56.99812+07	\N	f	\N
47	30	Phim hành động	f	2026-09-28 17:03:02.963765+07	\N	f	\N
48	30	CineBot rất vui được hỗ trợ bạn! Dựa trên sở thích bạn vừa chia sẻ, CineStream gợi ý bạn nên thưởng thức các tác phẩm: Avatar 3: Hỏa Ngục Pandora, Deadpool & Wolverine: Đa Vũ Trụ Hỗn Loạn, Xích Bích: Hỏa Thiêu Chiến Thuyền. Bạn có thể xem ngay danh sách bên dưới!	t	2026-09-28 17:03:02.963765+07	\N	f	\N
\.


--
-- TOC entry 5130 (class 0 OID 16930)
-- Dependencies: 237
-- Data for Name: Episodes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Episodes" ("Id", "SeasonId", "EpisodeNumber", "Title", "VideoUrl", "VideoStatus", "Duration", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
\.


--
-- TOC entry 5126 (class 0 OID 16894)
-- Dependencies: 233
-- Data for Name: Favorites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Favorites" ("UserId", "MovieId", "CreatedAt") FROM stdin;
2	29	2026-09-14 20:06:05.46123+07
30	32	2026-09-23 11:02:00.507313+07
\.


--
-- TOC entry 5121 (class 0 OID 16840)
-- Dependencies: 228
-- Data for Name: MovieCategories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MovieCategories" ("MovieId", "CategoryId") FROM stdin;
25	15
25	24
25	26
26	2
26	15
27	24
27	25
28	25
28	27
29	2
29	15
30	15
31	15
32	15
32	26
33	2
33	15
34	26
34	27
35	2
35	27
36	15
36	24
37	2
37	15
38	2
38	3
39	15
39	26
40	24
40	25
40	27
41	15
41	27
42	3
42	26
43	2
43	15
43	27
44	2
44	15
44	24
45	25
45	26
45	27
\.


--
-- TOC entry 5116 (class 0 OID 16800)
-- Dependencies: 223
-- Data for Name: Movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Movies" ("Id", "Title", "Description", "PosterUrl", "VideoUrl", "VideoStatus", "TrailerUrl", "Duration", "ReleaseYear", "Type", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt", "IsFeatured", "PublishStatus") FROM stdin;
29	Elephant's Dream (Giấc Mơ Cơ Khí)	Một chuyến du hành thị giác kỳ ảo vào bên trong cỗ máy khổng lồ vô tận, nơi hai nhân vật Proog và Emo đối mặt với những ảo ảnh cơ khí và sự bất đồng trong nhận thức thế giới.	https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600	/videos/Demo_2/master.m3u8	1	https://www.youtube.com/watch?v=TLkA0RELQ1E	11	2021	0	2026-09-09 18:43:52.305119+07	2026-09-28 16:58:07.844375+07	f	\N	f	2
35	Kỷ Nguyên Vũ Trụ: Hành Tinh Chết	Tàu thám hiểm viễn chinh đáp xuống một thiên thể bí ẩn ngoài rìa dải ngân hà và phát hiện tàn tích của một nền văn minh cổ đại đã bị diệt vong.	https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=TLkA0RELQ1E	125	2024	0	2026-09-18 20:11:40.485652+07	2026-09-28 16:58:07.848682+07	f	\N	f	2
36	Vua Bịp Ma Cao: Bão Táp Sòng Bạc	Những ván cược sinh tử cân não kết hợp yếu tố hài hước vui nhộn xoay quanh thiên tài bài bịp tái xuất giang hồ để lật đổ đế chế ngầm.	https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=600	/videos/Dai_thoai_tay_du/master.m3u8	1	https://www.youtube.com/watch?v=aqz-KE-bpKQ	94	2021	0	2026-09-18 20:11:40.485653+07	2026-09-28 16:58:07.84956+07	f	\N	f	2
25	Đại Thoại Tây Du (Châu Tinh Trì)	Tác phẩm kinh điển của điện ảnh Hồng Kông kết hợp giữa thần thoại Tây Du Ký và phong cách hài hước độc đáo của Châu Tinh Trì, kể về mối tình bi tráng giữa Tôn Ngộ Không (Chí Tôn Bảo) và Tử Hà Tiên Tử.	https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600	/videos/Dai_thoai_tay_du/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	106	1995	0	2026-09-09 18:43:52.304599+07	2026-09-28 16:58:07.836907+07	f	\N	t	2
27	Big Buck Bunny (Chú Thỏ Nổi Giận)	Bộ phim hoạt hình 3D nổi tiếng của Blender Foundation kể về cuộc trả đũa hài hước đầy sáng tạo của chú thỏ khổng lồ tốt bụng trước ba kẻ chuyên ức hiếp muôn thú trong rừng già.	https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600	/videos/Demo_2/master.m3u8	1	https://www.youtube.com/watch?v=aqz-KE-bpKQ	10	2023	0	2026-09-09 18:43:52.305118+07	2026-09-28 16:58:07.841965+07	f	\N	f	2
28	Sintel (Hành Trình Tìm Rồng)	Câu chuyện phiêu lưu xúc động về cô gái trẻ Sintel vượt qua sa mạc khắc nghiệt và vùng đất băng tuyết hiểm trở để tìm lại chú rồng nhỏ Scales mà cô đã cưu mang.	https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=eRsGyueVLvQ	15	2022	0	2026-09-09 18:43:52.305118+07	2026-09-28 16:58:07.843298+07	f	\N	f	2
30	Phim Test Da Sua	Phim thu nghiem tu dong dot 2	https://images.unsplash.com/photo-1489599849927-2ee91cede3ba	\N	1	\N	120	2026	0	2026-09-14 20:44:41.047792+07	2026-09-14 20:46:13.191401+07	t	2026-09-14 20:47:09.002929+07	f	0
26	Tears of Steel (Chiến Binh Thép)	Trong bối cảnh tương lai viễn tưởng tại Amsterdam, một nhóm các nhà khoa học và chiến binh cố gắng thay đổi quá khứ bằng công nghệ du hành thời gian để giải cứu nhân loại khỏi sự thống trị của đội quân robot.	https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	12	2024	0	2026-09-09 18:43:52.305118+07	2026-09-28 16:58:07.840436+07	f	\N	t	2
32	Lão Đạo Hỏa: Rực Lửa Chiến Tuyến	Bộ phim hành động hình sự kịch tính với những pha đối đầu tay đôi nghẹt thở giữa cảnh sát đặc nhiệm và băng đảng tội phạm nguy hiểm xuyên quốc gia.	https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	98	2023	0	2026-09-18 20:11:40.485651+07	2026-09-28 16:58:07.845677+07	f	\N	t	2
33	Cuộc Chiến Robot: Hậu Tận Thế	Sau khi trí tuệ nhân tạo mất kiểm soát, tàn tích nền văn minh con người phải tập hợp lực lượng cuối cùng để đánh sập máy chủ trung tâm bảo vệ sinh tồn.	https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600	/videos/Demo_2/master.m3u8	1	https://www.youtube.com/watch?v=TLkA0RELQ1E	115	2024	0	2026-09-18 20:11:40.485651+07	2026-09-28 16:58:07.846817+07	f	\N	f	2
34	Hiệp Khách Vô Danh: Phong Vân Tái Khởi	Hành trình rửa hận của tay kiếm cự phách chốn giang hồ, đối mặt với những cạm bẫy quyền mưu chốn triều đình và bí kíp võ học thất truyền.	https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=600	/videos/Dai_thoai_tay_du/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	102	2022	0	2026-09-18 20:11:40.485651+07	2026-09-28 16:58:07.84777+07	f	\N	f	2
31	The Ossydey	\N	\N	\N	0	\N	\N	\N	0	2026-09-18 13:58:43.75505+07	2026-09-19 09:44:05.422401+07	f	\N	f	0
37	Mật Vụ Băng Đăng: Lời Thề Danh Dự	Một chiến dịch tuyệt mật giữa vùng tuyết trắng Siberia, nơi ranh giới giữa chính nghĩa và phản bội bị xóa nhòa bởi tham vọng chính trị.	https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600	/videos/Demo_2/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	110	2023	0	2026-09-18 20:11:40.485654+07	2026-09-28 16:58:07.850676+07	f	\N	f	2
38	Mối Tình Ngân Hà: Vượt Thời Gian	Câu chuyện tình lãng mạn đầy xúc động giữa hai phi hành gia bị ngăn cách bởi độ trễ thời gian của hố đen vũ trụ vô tận.	https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=eRsGyueVLvQ	118	2022	0	2026-09-18 20:11:40.485655+07	2026-09-28 16:58:07.851703+07	f	\N	f	2
39	Xích Bích: Hỏa Thiêu Chiến Thuyền	Tái hiện trận đại chiến vang danh lịch sử thời Tam Quốc, nơi mưu trí của Gia Cát Lượng và Chu Du đối đầu cùng đại quân trăm vạn của Tào Tháo.	https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600	/videos/Dai_thoai_tay_du/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	135	2020	0	2026-09-18 20:11:40.485656+07	2026-09-28 16:58:07.852761+07	f	\N	f	2
40	Cuộc Phiêu Lưu Của Vẹt Xanh	Bộ phim hoạt hình rực rỡ sắc màu về hành trình trốn khỏi sở thú tìm đường trở về rừng nhiệt đới Amazon của chú vẹt tinh nghịch.	https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600	/videos/Demo_2/master.m3u8	1	https://www.youtube.com/watch?v=aqz-KE-bpKQ	88	2023	0	2026-09-18 20:11:40.485656+07	2026-09-28 16:58:07.853793+07	f	\N	f	2
41	Bản Đồ Kho Báu Rừng Amazon	Đoàn khảo cổ liều lĩnh thâm nhập sâu vào rừng rậm nhiệt đới để tìm kiếm thành phố vàng El Dorado được ghi chép trong truyền thuyết.	https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=TLkA0RELQ1E	104	2024	0	2026-09-18 20:11:40.485656+07	2026-09-28 16:58:07.854727+07	f	\N	f	2
42	Thần Điêu Hiệp Lữ: Kiếm Vũ Giang Hồ	Mối tình thủy chung son sắt chốn võ lâm kiếm hiệp cùng những màn thi triển khinh công và kiếm pháp kỳ ảo đỉnh cao.	https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600	/videos/Dai_thoai_tay_du/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	112	2021	0	2026-09-18 20:11:40.485656+07	2026-09-28 16:58:07.855628+07	f	\N	f	2
43	Avatar 3: Hỏa Ngục Pandora	Phần tiếp theo của siêu phẩm điện ảnh toàn cầu khám phá tộc người Tro Tàn (Ash People) bí hiểm và hung bạo trên mặt trăng Pandora.	https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600	/videos/lao_dao_hoa/master.m3u8	1	https://www.youtube.com/watch?v=R6MlUcmOul8	165	2026	0	2026-09-18 20:11:40.485657+07	2026-09-28 16:58:07.856848+07	f	\N	f	1
44	Deadpool & Wolverine: Đa Vũ Trụ Hỗn Loạn	Sự kết hợp không tưởng giữa hai dị nhân biểu tượng trong một nhiệm vụ xuyên không gian cứu rỗi dòng thời gian Marvel.	https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600	/videos/Demo_2/master.m3u8	1	https://www.youtube.com/watch?v=TLkA0RELQ1E	127	2026	0	2026-09-18 20:11:40.485657+07	2026-09-28 16:58:07.858569+07	f	\N	f	1
45	Tôn Ngộ Không: Đại Náo Tam Giới	Bản hoạt họa kỹ xảo 3D đỉnh cao tái hiện hành trình tầm sư học đạo và cuộc đại chiến kinh thiên động địa trên Thiên Cung.	https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600	/videos/Dai_thoai_tay_du/master.m3u8	1	https://www.youtube.com/watch?v=aqz-KE-bpKQ	95	2026	0	2026-09-18 20:11:40.485657+07	2026-09-28 16:58:07.860092+07	f	\N	f	1
\.


--
-- TOC entry 5132 (class 0 OID 16964)
-- Dependencies: 239
-- Data for Name: PaymentTransactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PaymentTransactions" ("Id", "UserId", "OrderCode", "Amount", "PlanDurationDays", "Status", "PaymentGateway", "GatewayTransactionId", "CompletedAt", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
1	2	CINE26091113555346	50000.00	30	1	SePay_MB	FT260911999901	2026-09-11 20:55:53.502731+07	2026-09-11 20:55:53.084349+07	2026-09-11 20:55:53.503184+07	f	\N
2	2	CINE26091113555357	135000.00	90	1	SePay_MB	SIMULATED_e9f5aa27	2026-09-11 20:55:53.712687+07	2026-09-11 20:55:53.632817+07	2026-09-11 20:55:53.712714+07	f	\N
3	2	CINE26091113562392	50000.00	30	1	SePay_MB	FT260911999901	2026-09-11 20:56:23.400539+07	2026-09-11 20:56:23.369824+07	2026-09-11 20:56:23.400547+07	f	\N
4	2	CINE26091113562332	135000.00	90	1	SePay_MB	SIMULATED_c188d936	2026-09-11 20:56:23.471021+07	2026-09-11 20:56:23.429785+07	2026-09-11 20:56:23.471023+07	f	\N
5	2	CINE26091413062036	50000.00	30	0	SePay_MB	\N	\N	2026-09-14 20:06:20.586898+07	\N	f	\N
6	2	CINE26091413065232	50000.00	30	0	SePay_MB	\N	\N	2026-09-14 20:06:52.809935+07	\N	f	\N
7	1	CINE26091602063079	2000.00	30	1	SePay_MB	SIMULATED_774a5d3e	2026-09-16 09:08:01.755465+07	2026-09-16 09:06:30.256365+07	2026-09-16 09:08:01.75585+07	f	\N
8	30	CINE26092303571048	2000.00	30	0	SePay_MB	\N	\N	2026-09-23 10:57:10.642399+07	\N	f	\N
10	1	CINE26092304003971	5000.00	90	1	SePay_MB	SIMULATED_20cbcc88	2026-09-23 11:01:27.285755+07	2026-09-23 11:00:39.841894+07	2026-09-23 11:01:27.286016+07	f	\N
9	30	CINE26092303591616	2000.00	30	1	SePay_MB	SIMULATED_23a8895c	2026-09-23 11:01:35.333888+07	2026-09-23 10:59:16.193046+07	2026-09-23 11:01:35.33392+07	f	\N
11	30	CINE26092310043912	2000.00	30	0	SePay_MB	\N	\N	2026-09-23 17:04:39.441572+07	\N	f	\N
12	30	CINE26092414105742	5000.00	90	1	SePay_MB	FT26267296095949	2026-09-24 21:11:20.158394+07	2026-09-24 21:10:57.364199+07	2026-09-24 21:11:20.158861+07	f	\N
13	30	CINE26092503483690	5000.00	90	0	SePay_MB	\N	\N	2026-09-25 10:48:36.128817+07	\N	f	\N
\.


--
-- TOC entry 5128 (class 0 OID 16913)
-- Dependencies: 235
-- Data for Name: Profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Profiles" ("Id", "UserId", "DisplayName", "AvatarUrl", "Bio", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
1	1	Quản Trị Viên CineStream	https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150	Tài khoản quản trị hệ thống	2026-09-06 20:48:48.588574+07	\N	f	\N
2	2	Kiem Thu Vien CineStream	https://images.unsplash.com/photo-1535713875002-d1d0cf377fde	Thanh vien yeu thich phim hanh dong	2026-09-06 20:48:48.990169+07	\N	f	\N
20	28	testuser_temp	\N	\N	2026-09-15 16:20:09.938788+07	\N	f	\N
21	29	user01	\N	\N	2026-09-16 10:40:50.356769+07	\N	f	\N
22	30	user02	\N	\N	2026-09-16 11:15:43.281799+07	\N	f	\N
23	31	nkda20	\N	\N	2026-09-16 12:33:13.015977+07	\N	f	\N
25	33	nkda941	\N	\N	2026-09-16 12:52:16.736219+07	\N	f	\N
26	34	freeuser	\N	\N	2026-09-19 09:17:36.82837+07	\N	f	\N
\.


--
-- TOC entry 5123 (class 0 OID 16858)
-- Dependencies: 230
-- Data for Name: Seasons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Seasons" ("Id", "SeriesId", "SeasonNumber", "Title", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
\.


--
-- TOC entry 5118 (class 0 OID 16814)
-- Dependencies: 225
-- Data for Name: Series; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Series" ("Id", "Title", "Description", "PosterUrl", "TrailerUrl", "ReleaseYear", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
\.


--
-- TOC entry 5134 (class 0 OID 16986)
-- Dependencies: 241
-- Data for Name: SystemSettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SystemSettings" ("Id", "Key", "Value", "Description", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt") FROM stdin;
\.


--
-- TOC entry 5120 (class 0 OID 16826)
-- Dependencies: 227
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Username", "Email", "PasswordHash", "Role", "CreatedAt", "UpdatedAt", "IsDeleted", "DeletedAt", "EmailConfirmationToken", "EmailConfirmationTokenExpiresAt", "IsEmailConfirmed", "PasswordResetToken", "PasswordResetTokenExpiresAt", "IsLocked", "LockReason", "IsPremium", "PremiumExpiresAt") FROM stdin;
2	user	user@cinestream.com	$2a$11$1fBLbUOi9OHzuiEYmZ3.LeBAMTod00kK.w9ZUwNJDKrvlFTJmjSOi	0	2026-09-06 20:48:48.589399+07	2026-09-19 17:37:32.373129+07	f	\N	\N	\N	t	\N	\N	f	\N	t	2026-10-19 17:37:32.373128+07
29	user01	nkda2k5@gmail.com	$2a$11$lrTaVG.sOXhfwNDphmz4Vub1Ma1y4uF5xHIKM5B5BmM58Xz/URN5G	0	2026-09-16 10:40:50.356299+07	2026-09-16 11:14:52.404933+07	t	2026-09-23 10:50:44.767825+07	\N	\N	t	\N	\N	f	\N	f	\N
28	testuser_temp	testuser_temp@cinestream.com	$2a$11$U02QmJrCuxYn9aQS5bdzSOR5WvZLCqWXCtXXjQiJUpBxwWx5ZFxKG	0	2026-09-15 16:20:09.938359+07	2026-09-15 16:24:37.55375+07	t	2026-09-15 16:25:21.745403+07	755821	2026-09-16 16:20:09.938735+07	f	\N	\N	f	\N	f	\N
1	admin	admin@cinestream.com	$2a$11$JeAKlIX126APN2b/M/py8./PjsigHH.PbZAf83aKwER4XKswlCXt.	1	2026-09-06 20:48:47.583212+07	2026-09-23 11:01:27.286987+07	f	\N	\N	\N	t	\N	\N	f	\N	t	2027-01-14 09:08:01.764701+07
30	user02	duck2k5@gmail.com	$2a$11$EGZQ7nOuAIaTfBdaiDyQmOkSl0YjQndf8Q.ylWHcEY81ES3IXhTR.	0	2026-09-16 11:15:43.281798+07	2026-09-24 21:11:20.16731+07	f	\N	\N	\N	t	\N	\N	f	\N	t	2027-01-21 11:01:35.334186+07
31	nkda20	nkda941@gmail.com	$2a$11$csHkkKda/3KShF25bjA4teUIl5FDwIQdShhM98HJuYoJ6fgRROU9K	0	2026-09-16 12:33:13.015974+07	\N	f	\N	756885	2026-09-17 12:33:13.015975+07	f	\N	\N	f	\N	f	\N
33	nkda941	s2952005@gmail.com	$2a$11$uU6XQZQh82neuDtbmoUi7elI6TioB70RW.q5FzxdLlNj51lfsBeQe	0	2026-09-16 12:52:16.735808+07	\N	f	\N	704646	2026-09-17 12:52:16.736113+07	f	\N	\N	f	\N	f	\N
34	freeuser	freeuser@cinestream.com	$2a$11$W9R3Zi8l8OAF/JXs9RctPOxfOEXvJ7ueGgBD1DAEjZO9SHeVtvYES	0	2026-09-19 09:17:36.828008+07	\N	f	\N	544111	2026-09-20 09:17:36.828315+07	f	\N	\N	f	\N	f	\N
\.


--
-- TOC entry 5112 (class 0 OID 16780)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260906113744_InitialCreate	10.0.11
20260909130232_AddAdvancedAuthFieldsToUser	10.0.11
20260910061915_AddLockFieldsToUser	10.0.11
20260911023010_AddPremiumSubscriptionToUser	10.0.11
20260911125602_AddPaymentTransactions	10.0.11
20260915145248_AddSystemSettings	10.0.11
20260918062018_AddIsFeaturedToMovie	10.0.11
20260918072920_AddMoviePublishStatus	10.0.11
\.


--
-- TOC entry 5140 (class 0 OID 0)
-- Dependencies: 220
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 28, true);


--
-- TOC entry 5141 (class 0 OID 0)
-- Dependencies: 231
-- Name: ChatLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ChatLogs_Id_seq"', 48, true);


--
-- TOC entry 5142 (class 0 OID 0)
-- Dependencies: 236
-- Name: Episodes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Episodes_Id_seq"', 1, false);


--
-- TOC entry 5143 (class 0 OID 0)
-- Dependencies: 222
-- Name: Movies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Movies_Id_seq"', 45, true);


--
-- TOC entry 5144 (class 0 OID 0)
-- Dependencies: 238
-- Name: PaymentTransactions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PaymentTransactions_Id_seq"', 13, true);


--
-- TOC entry 5145 (class 0 OID 0)
-- Dependencies: 234
-- Name: Profiles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Profiles_Id_seq"', 26, true);


--
-- TOC entry 5146 (class 0 OID 0)
-- Dependencies: 229
-- Name: Seasons_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Seasons_Id_seq"', 1, false);


--
-- TOC entry 5147 (class 0 OID 0)
-- Dependencies: 224
-- Name: Series_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Series_Id_seq"', 1, false);


--
-- TOC entry 5148 (class 0 OID 0)
-- Dependencies: 240
-- Name: SystemSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SystemSettings_Id_seq"', 4, true);


--
-- TOC entry 5149 (class 0 OID 0)
-- Dependencies: 226
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 34, true);


--
-- TOC entry 4922 (class 2606 OID 16798)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- TOC entry 4939 (class 2606 OID 16888)
-- Name: ChatLogs PK_ChatLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ChatLogs"
    ADD CONSTRAINT "PK_ChatLogs" PRIMARY KEY ("Id");


--
-- TOC entry 4948 (class 2606 OID 16942)
-- Name: Episodes PK_Episodes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Episodes"
    ADD CONSTRAINT "PK_Episodes" PRIMARY KEY ("Id");


--
-- TOC entry 4942 (class 2606 OID 16901)
-- Name: Favorites PK_Favorites; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "PK_Favorites" PRIMARY KEY ("UserId", "MovieId");


--
-- TOC entry 4933 (class 2606 OID 16846)
-- Name: MovieCategories PK_MovieCategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCategories"
    ADD CONSTRAINT "PK_MovieCategories" PRIMARY KEY ("MovieId", "CategoryId");


--
-- TOC entry 4924 (class 2606 OID 16812)
-- Name: Movies PK_Movies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Movies"
    ADD CONSTRAINT "PK_Movies" PRIMARY KEY ("Id");


--
-- TOC entry 4952 (class 2606 OID 16977)
-- Name: PaymentTransactions PK_PaymentTransactions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PaymentTransactions"
    ADD CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id");


--
-- TOC entry 4945 (class 2606 OID 16923)
-- Name: Profiles PK_Profiles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles"
    ADD CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id");


--
-- TOC entry 4936 (class 2606 OID 16869)
-- Name: Seasons PK_Seasons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Seasons"
    ADD CONSTRAINT "PK_Seasons" PRIMARY KEY ("Id");


--
-- TOC entry 4926 (class 2606 OID 16824)
-- Name: Series PK_Series; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Series"
    ADD CONSTRAINT "PK_Series" PRIMARY KEY ("Id");


--
-- TOC entry 4955 (class 2606 OID 16997)
-- Name: SystemSettings PK_SystemSettings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SystemSettings"
    ADD CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id");


--
-- TOC entry 4930 (class 2606 OID 16839)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4919 (class 2606 OID 16786)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4920 (class 1259 OID 16948)
-- Name: IX_Categories_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Categories_Name" ON public."Categories" USING btree ("Name");


--
-- TOC entry 4937 (class 1259 OID 16949)
-- Name: IX_ChatLogs_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ChatLogs_UserId" ON public."ChatLogs" USING btree ("UserId");


--
-- TOC entry 4946 (class 1259 OID 16950)
-- Name: IX_Episodes_SeasonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Episodes_SeasonId" ON public."Episodes" USING btree ("SeasonId");


--
-- TOC entry 4940 (class 1259 OID 16951)
-- Name: IX_Favorites_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Favorites_MovieId" ON public."Favorites" USING btree ("MovieId");


--
-- TOC entry 4931 (class 1259 OID 16952)
-- Name: IX_MovieCategories_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MovieCategories_CategoryId" ON public."MovieCategories" USING btree ("CategoryId");


--
-- TOC entry 4949 (class 1259 OID 16983)
-- Name: IX_PaymentTransactions_OrderCode; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PaymentTransactions_OrderCode" ON public."PaymentTransactions" USING btree ("OrderCode");


--
-- TOC entry 4950 (class 1259 OID 16984)
-- Name: IX_PaymentTransactions_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PaymentTransactions_UserId" ON public."PaymentTransactions" USING btree ("UserId");


--
-- TOC entry 4943 (class 1259 OID 16953)
-- Name: IX_Profiles_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Profiles_UserId" ON public."Profiles" USING btree ("UserId");


--
-- TOC entry 4934 (class 1259 OID 16954)
-- Name: IX_Seasons_SeriesId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Seasons_SeriesId" ON public."Seasons" USING btree ("SeriesId");


--
-- TOC entry 4953 (class 1259 OID 16998)
-- Name: IX_SystemSettings_Key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_SystemSettings_Key" ON public."SystemSettings" USING btree ("Key");


--
-- TOC entry 4927 (class 1259 OID 16955)
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- TOC entry 4928 (class 1259 OID 16956)
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public."Users" USING btree ("Username");


--
-- TOC entry 4959 (class 2606 OID 16889)
-- Name: ChatLogs FK_ChatLogs_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ChatLogs"
    ADD CONSTRAINT "FK_ChatLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4963 (class 2606 OID 16943)
-- Name: Episodes FK_Episodes_Seasons_SeasonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Episodes"
    ADD CONSTRAINT "FK_Episodes_Seasons_SeasonId" FOREIGN KEY ("SeasonId") REFERENCES public."Seasons"("Id") ON DELETE CASCADE;


--
-- TOC entry 4960 (class 2606 OID 16902)
-- Name: Favorites FK_Favorites_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- TOC entry 4961 (class 2606 OID 16907)
-- Name: Favorites FK_Favorites_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4956 (class 2606 OID 16847)
-- Name: MovieCategories FK_MovieCategories_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCategories"
    ADD CONSTRAINT "FK_MovieCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- TOC entry 4957 (class 2606 OID 16852)
-- Name: MovieCategories FK_MovieCategories_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCategories"
    ADD CONSTRAINT "FK_MovieCategories_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- TOC entry 4964 (class 2606 OID 16978)
-- Name: PaymentTransactions FK_PaymentTransactions_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PaymentTransactions"
    ADD CONSTRAINT "FK_PaymentTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4962 (class 2606 OID 16924)
-- Name: Profiles FK_Profiles_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles"
    ADD CONSTRAINT "FK_Profiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4958 (class 2606 OID 16870)
-- Name: Seasons FK_Seasons_Series_SeriesId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Seasons"
    ADD CONSTRAINT "FK_Seasons_Series_SeriesId" FOREIGN KEY ("SeriesId") REFERENCES public."Series"("Id") ON DELETE CASCADE;


-- Completed on 2026-09-28 21:14:44

--
-- PostgreSQL database dump complete
--

\unrestrict nAnxykeZm3V7XfvOrNjJabghNma3UeKKMDIVtUMJLNuCZscivrXTNnVbfYoFSXT

